### ISSUE TITLE
Totally not working in Chrome

### ISSUE THREAD

**Issue by marcomarsala** [misthero/SlidersEverywhere#1] opened 2014-12-01 20:42 UTC
The slider is totally not working in Google Chrome latest version: Try here: http://www.laboratoriocanevari.it/content/8-il-laboratorio

**Comment by misthero** [comment] 2014-12-01 21:44
hope you are not using version 1.6.2 from github, it is old, anyway I cannot replicate your issue, it works on chrome with every transition, slide, fade, etc..

**Comment by marcomarsala** [comment] 2014-12-01 21:50
I’m using 1.6.38, but on latest Chrome works only Fade transition  tested on three different PCs:
Win8 + Chrome
Win7 (my office) + Chrome
Win7 (my notebook) + Chrome

**Comment by misthero** [comment] 2014-12-01 22:04
can you tell me if this works for you on chrome?
prestashop 1.6+: http://development.syncrea.it/presta6
prestashop 1.5+: http://development.syncrea.it/presta

if it is working you could have an issue with your theme not related with the module

**Comment by marcomarsala** [comment] 2014-12-02 13:46
It is working in your site. So the plugin is incompatible with Dilecta theme except for the Fade transition, that is working.

**Comment by misthero** [comment] 2014-12-02 14:25
maybe some css rule from your theme prevents the slider from working correctly, if you can show me a page with the transitions not working I can chek where the problem is and help you with it. but please refer to the forums for this kind of help requests:
english support forum: http://www.prestashop.com/forums/index.php?showtopic=310597
italian support forum: http://www.prestashop.com/forums/index.php?showtopic=343799

I'm closing the issue here on git.

thank you

**Closed as completed by misthero** 2014-12-02 14:25 UTC
